!pip install numpy

In [19]:
import numpy as np

配列を作る

In [25]:
a = np.array([1,2,3])
a

array([1, 2, 3])

インデックスを指定して要素を取り出す。ここらへんはPythonとほぼ同じ

In [6]:
print(f"{a[0],a[1],a[2]}")

(1, 2, 3)


In [7]:
a[0]

1

二次元の配列

In [10]:
a = np.array([
    [1,2,3],
    [4,5,6]
])
#a = np.array([[1,2,3],[4,5,6]])

In [11]:
a

array([[1, 2, 3],
       [4, 5, 6]])

インデックスを指定して要素を取り出す。単に[0]を指定しただけだと、リストの一番目を取得することに注意

In [12]:
a[0]

array([1, 2, 3])

In [13]:
a[0][1]

2

In [14]:
a[1][0]

4

numpyに渡したデータの構造が分かる

In [15]:
a.shape

(2, 3)

何次元かわかる

In [16]:
a.ndim

2

データの数を調べる

In [17]:
a.size

6

numpyで配列を作る  
0から10までのリストを作る

In [18]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

0から30まで、5刻みの配列を作る

In [20]:
a = np.arange(0,30,5)
a

array([ 0,  5, 10, 15, 20, 25])

データ構造を決めつつ、リストの要素を全て0で埋める

In [24]:
a = np.zeros((3,4))
a

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

zerosで要素のデータタイプを指定することもできる

In [29]:
a = np.zeros((3,4), dtype=np.int16)
a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

0ではなく、1でも埋められる

In [30]:
a = np.ones((3,4), dtype=np.int16)
a

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

PythonのNoneとほぼ同じなnumpyのnan

In [31]:
np.nan

nan

配列にすることもできる

In [33]:
[np.nan] * 10

[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]

指定した引数間で指定した数の要素を作る

In [34]:
a = np.linspace(0,5,10)
a

array([ 0.        ,  0.55555556,  1.11111111,  1.66666667,  2.22222222,
        2.77777778,  3.33333333,  3.88888889,  4.44444444,  5.        ])

0から5までの間で、10個要素を作成できた

作成した配列の構造を指定する

In [40]:
a = np.arange(24).reshape(2,3,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

reshapeの引数として  
第一引数・・・何次元のリストにするか決める  
第二、第三引数・・・何行何列を指定

In [42]:
#ただし、一度変数に入れた配列をreshapeしても上記にはならないことに注意
a = np.arange(24)
a.reshape(2,3,4)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

たくさんのデータを表示すると省略が発生する

In [43]:
a = np.arange(10000)
a

array([   0,    1,    2, ..., 9997, 9998, 9999])

2次元リストに分けても同様である

In [45]:
a = np.arange(10000).reshape(100,100)
a

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ..., 
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

これを省略することなく表示させたい場合は以下を入力する

In [46]:
np.set_printoptions(threshold=10000)

以下の配列を用意する

In [55]:
a = np.arange(0,10,2)
b = np.arange(5)
c = np.arange(0,13,3)

In [56]:
a

array([0, 2, 4, 6, 8])

In [57]:
b

array([0, 1, 2, 3, 4])

In [58]:
c

array([ 0,  3,  6,  9, 12])

配列をappendしてみる

In [59]:
np.append(a,b)

array([0, 2, 4, 6, 8, 0, 1, 2, 3, 4])

vstackを利用すると、多次元配列を作ることが可能

In [60]:
np.vstack([a,b,c])

array([[ 0,  2,  4,  6,  8],
       [ 0,  1,  2,  3,  4],
       [ 0,  3,  6,  9, 12]])

ただし、注意点として、それぞれの配列の要素数が同じでないと上記はできない

それぞれの配列を足して一次元リストが作成できる

In [64]:
np.hstack([a,b,c])

array([ 0,  2,  4,  6,  8,  0,  1,  2,  3,  4,  0,  3,  6,  9, 12])

配列同士の計算について

In [7]:
a = np.array([5,10,15,20,25])
b = np.arange(0,5)

In [8]:
a

array([ 5, 10, 15, 20, 25])

In [9]:
b

array([0, 1, 2, 3, 4])

In [13]:
#和
add = a + b

#差
sub = a - b

#積
multi = a * b

#除
#0が含まれエラーが発生するため行わない
print(add)
print(sub)
print(multi)

[ 5 11 17 23 29]
[ 5  9 13 17 21]
[  0  10  30  60 100]


配列の中で条件に合致するものをbool型で返す  
以下だと配列aで10より大きいものはTrueを返す

In [17]:
a > 10

array([False, False,  True,  True,  True], dtype=bool)

配列の各要素全てに演算を行う

In [21]:
a = np.ones((2,3),dtype=int)
a

array([[1, 1, 1],
       [1, 1, 1]])

試しに演算を行ってみる

In [22]:
a *= 5
a

array([[5, 5, 5],
       [5, 5, 5]])

他の複合代入演算も同様に行うことができる

In [24]:
a += 2
a

array([[9, 9, 9],
       [9, 9, 9]])

データ構造を指定しつつ、配列にランダムな値を入れる

In [28]:
a = np.random.random((3,4))
a

array([[ 0.95214713,  0.0827671 ,  0.93031511,  0.0557579 ],
       [ 0.87756191,  0.83644114,  0.16183263,  0.84757523],
       [ 0.05279468,  0.4243658 ,  0.26618186,  0.97035936]])

配列の要素の和を求める

In [29]:
a.sum()

6.4580998503015632

最小を求める

In [30]:
a.min()

0.05279467817936101

最大を求める

In [32]:
a.max()

0.97035935956748931

平均を求める

In [33]:
a.mean()

0.53817498752513027

列または行毎の和を求める

次の配列があるとする

In [34]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

列毎の和を求める  
axis=0で列  
axis=1で行をそれぞれ指定

In [35]:
a.sum(axis=0)

array([12, 15, 18, 21])

In [36]:
a.sum(axis=1)

array([ 6, 22, 38])

転置を行う

In [38]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

既存のデータ構造を変更する

In [40]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [44]:
a.size

12

In [46]:
a.resize(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])